name: ci-lahaina-sim

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    runs-on: local

    steps:
      - name: Cache node modules
        run: |
          # Your local cache logic goes here

      - name: Setup Node.js
        run: |
          # Your local Node.js setup logic goes here

      - name: Install npm dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Meteor
        run: curl https://install.meteor.com/ | sh

      - name: Run Meteor commands
        run: |
          meteor npm install
          meteor npm run lint
          # meteor npm run testcafe-ci (Uncomment if needed)